name:                postscript-transformer
version:             0.1.0.0
github:              "kowaalczyk/postscript-transformer"
license:             BSD3
author:              "Krzysztof Kowalczyk"
maintainer:          "kk385830@students.mimuw.edu.pl"
copyright:           "2019 Krzysztof Kowalczyk"

extra-source-files:
- README.md
- Assignment.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/postscript-transformer#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  postscript-transformer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - postscript-transformer
    - mtl

tests:
  postscript-transformer-test:
    main:                TestTransform.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - postscript-transformer
    - QuickCheck
